name: Run Stock Investment Algorithm

on:
  schedule:
    # Run every hour (adjust cron for desired schedule)
    - cron: "0 * * * *"

jobs:
  run-algorithm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pandas numpy yfinance matplotlib scikit-learn requests

      - name: Run Script
        run: |
          python stock_investment_algorithm.py
